@startuml

skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}
participant Actor
Actor -> XmlBeanDefinitionReader : doLoadBeanDefinitions
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader : doLoadDocument
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader : getValidationModeForResource
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader --> XmlBeanDefinitionReader
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> DocumentLoader : loadDocument
activate DocumentLoader
DocumentLoader --> XmlBeanDefinitionReader
deactivate DocumentLoader
XmlBeanDefinitionReader --> XmlBeanDefinitionReader
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader : registerBeanDefinitions
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader : createBeanDefinitionDocumentReader
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader --> XmlBeanDefinitionReader
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> XmlBeanDefinitionReader : createReaderContext
activate XmlBeanDefinitionReader
XmlBeanDefinitionReader --> XmlBeanDefinitionReader
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> BeanDefinitionDocumentReader : registerBeanDefinitions
activate BeanDefinitionDocumentReader
BeanDefinitionDocumentReader --> XmlBeanDefinitionReader
deactivate BeanDefinitionDocumentReader
XmlBeanDefinitionReader --> XmlBeanDefinitionReader
deactivate XmlBeanDefinitionReader
XmlBeanDefinitionReader -> Log : debug
activate Log
Log --> XmlBeanDefinitionReader
deactivate Log
return
@enduml