@startuml


skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}
participant Actor
Actor -> DefaultBeanDefinitionDocumentReader : registerBeanDefinitions
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader : doRegisterBeanDefinitions
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader : createDelegate
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader --> DefaultBeanDefinitionDocumentReader
deactivate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader -> BeanDefinitionParserDelegate : isDefaultNamespace
activate BeanDefinitionParserDelegate
BeanDefinitionParserDelegate --> DefaultBeanDefinitionDocumentReader
deactivate BeanDefinitionParserDelegate
DefaultBeanDefinitionDocumentReader -> Element : getAttribute
activate Element
Element --> DefaultBeanDefinitionDocumentReader
deactivate Element
DefaultBeanDefinitionDocumentReader -> StringUtils : hasText
activate StringUtils
StringUtils --> DefaultBeanDefinitionDocumentReader
deactivate StringUtils
DefaultBeanDefinitionDocumentReader -> StringUtils : tokenizeToStringArray
activate StringUtils
StringUtils --> DefaultBeanDefinitionDocumentReader
deactivate StringUtils
DefaultBeanDefinitionDocumentReader -> Environment : acceptsProfiles
activate Environment
Environment --> DefaultBeanDefinitionDocumentReader
deactivate Environment
DefaultBeanDefinitionDocumentReader -> Log : debug
activate Log
Log --> DefaultBeanDefinitionDocumentReader
deactivate Log
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader : preProcessXml
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader --> DefaultBeanDefinitionDocumentReader
deactivate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader : parseBeanDefinitions
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader --> DefaultBeanDefinitionDocumentReader
deactivate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader -> DefaultBeanDefinitionDocumentReader : postProcessXml
activate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader --> DefaultBeanDefinitionDocumentReader
deactivate DefaultBeanDefinitionDocumentReader
DefaultBeanDefinitionDocumentReader --> DefaultBeanDefinitionDocumentReader
deactivate DefaultBeanDefinitionDocumentReader
return
@enduml